# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 163a513f751997f7fc2e53f8235f56928ce7e023fca32fdf92e33209311e4093676c5896fbd8c10d25438f7e8f08d6fb582fce630bf9280921efab9194a9e934

test:
  secret_key_base: 3603cb3c5d64444c87887642ef1784108ac08a8c80dc97189211ba05cf7cf5718a99fe1834b9b5cf67f8727c18da2f5c8101ba63a613ba4c30a54425aba09c02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
